name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build application
        shell: bash
        run: |
          npm install
          git config user.name "BryceJensenius"
          git config user.email "brycejensenius@gmail.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          npm run build
          npm run deploy